name: "backend-ci-cd"
on:
   pull_request:
       branches: ["main"]
       paths:
       - "backend/**"
   push: 
     branches: [ "main" ]
     paths:
     - "backend/**"

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
         
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 2.7.4 
          bundler-cache: true
          working-directory: "./backend"
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
        working-directory: "./backend"
      # Add or replace test runners here
      - name: Run tests
        run:  bin/rake
        working-directory: "./backend"
  deployment:
  
   runs-on: ubuntu-latest
   needs: [testing]
   
   steps:
   - name: "Deploy to render"
     uses: johnbeynon/render-deploy-action@v0.0.8
     with:
          service-id: ${{ secrets.SERVICE_ID_BACKEND }}
          api-key: ${{ secrets.RENDER_API_KEY_BACKEND }}
